### ISSUE TITLE
Carousel Slamming

### ISSUE THREAD

**Issue by parkersonik** [Wikiki/bulma-carousel#1]
When setting the fade effect, the carousel collapses, decided as follows:
```
.carousel-item.is-active {
    position: relative !important;
}
```
It would be nice to set the auto-sliding option ...

**Comment by Wikiki** [comment]
Hi @parkersonik,

to fix that I set an height to .carousel element <code>style="height: 350px;"</code>.

I'm trying to find a way to manage it better.

**Comment by Wikiki** [comment]
Auto-sliding option has been added. Please see documentation page.
