### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by melTr** [Wikiki/bulma-carousel#10]
Hi
Have difficulties to install the extension. 
Where bulma-caroussel folder should be? In the same folder than bulma.css ? Or anywhere?
Furthermore in https://wikiki.github.io/components/carousel/ it's written
`<script type="text/javascript" src="./carousel.min.js"></script>`
however, the file is named bulma-caroussel.min.js in the extension's folder. 
Where this could should go? In head or before the end of file?

For now, with your example code, I get images and controls but no caroussel (even if js file is loaded). 
![image](https://user-images.githubusercontent.com/1063951/36075979-1ea92046-0f24-11e8-87bf-e1181bb1d1fb.png)
Thanks
Mel

**Comment by Wikiki** [comment]
I fixed the documentation.
The JavaScript file path depends on the way you installed the extension.

If you used NPM then use the following url: '/node_modules/bulma-extensions/bulma-carousel/dist/bulma-carousel.min.js'

**Comment by melTr** [comment]
Finally get it working by adding       
<link rel="stylesheet" type="text/css" href="../dist/bulma-carousel.min.css">
It's not written anywhere in documentation. Could you mention it somehow?

**Comment by rppf** [comment]
I have the same issue. @melTr , kindly show me your solution. 
This is how I import in
app.scss
![](https://i.imgur.com/HVNYc6O.png)
and in app.js
![](https://i.imgur.com/ezSisF2.png)
and this is how I link in my index
![](https://i.imgur.com/03EC7gW.png)

By the way I'm using Laravel, VueJS, Bulma, Laravel Mix, and webpack.

**Comment by JohnLea83** [comment]
@melTr How did you get this working?

**Comment by melTr** [comment]
If I remembered correctly, js was not a problem, but I did a stupid error, I forgot to put css in head. Something like this:
<link rel="stylesheet" type="text/css" href="./styles/dist/bulma-carousel.min.css" />
Hope it helps.

**Comment by Wikiki** [comment]
hi @JohnLea83 thanks for the help.
@melTr can you confirm this fix your issue ?

**Comment by JohnLea83** [comment]
@Wikiki Oh, to be honest, I wasn't trying to help. I was trying to find any way to get your code to work in my Angular app. And since your general response to this type of query is "I don't use Angular" followed up with closing the request, I'm left with asking people who tried the same sort of thing I'm trying now.

Also, thank you, @melTr, for your response.

**Comment by Wikiki** [comment]
My bad I mix up the names when commenting.
That's right, I'm not using angular ;-) but if any of you have time to exchange on the best way to enhance the extension to ease the angular integration I'm aware.

**Comment by LemonDunk** [comment]
i have the same problem pls help me
this is my code:

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>ISHRM TVET</title>

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css">
	<link rel="stylesheet" type="text/css" href="style.css">
	<script src="https://kit.fontawesome.com/58878612c2.js"></script>
	<link rel="stylesheet" type="text/css" href="dist/css/bulma-carousel.min.css">
	<script type="text/javascript" src="dist/js/bulma-carousel.js"></script>
	<script
 	src="https://code.jquery.com/jquery-3.4.1.min.js"
  	integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  	crossorigin="anonymous"></script>

<body>
<div class='carousel carousel-animated carousel-animate-slide'>
  <div class='carousel-container'>
    <div class='carousel-item has-background is-active'>
      <img class="is-background" src="https://wikiki.github.io/images/merry-christmas.jpg" alt="" width="640" height="310" />
      <div class="title">Merry Christmas</div>
    </div>
    <div class='carousel-item has-background'>
      <img class="is-background" src="https://wikiki.github.io/images/singer.jpg" alt="" width="640" height="310" />
      <div class="title">Original Gift: Offer a song with <a href="https://lasongbox.com" target="_blank">La Song Box</a></div>
    </div>
    <div class='carousel-item has-background'>
      <img class="is-background" src="https://wikiki.github.io/images/sushi.jpg" alt="" width="640" height="310" />
      <div class="title">Sushi time</div>
    </div>
    <div class='carousel-item has-background'>
      <img class="is-background" src="https://wikiki.github.io/images/life.jpg" alt="" width="640" height="310" />
      <div class="title">Life</div>
    </div>
  </div>
  <div class="carousel-navigation">
    <div class="carousel-nav-left">
      <i class="fa fa-chevron-left" aria-hidden="true"></i>
    </div>
    <div class="carousel-nav-right">
      <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </div>
  </div>
</div>



<script src="https://cdn.jsdelivr.net/npm/bulma-carousel@3.0.0/dist/js/bulma-carousel.min.js"></script>
<script>
  $(document).ready(function(){
         var carousels = bulmaCarousel.attach(); // carousels now contains an array of all Carousel instances
     });
</script>
	
	
	


</body>
</html>
