### ISSUE TITLE
Carousel not animating with Nuxt

### ISSUE THREAD

**Issue by o1lab** [Wikiki/bulma-carousel#13]
Im using this carousel within a nuxt app (vuejs framework) - carousel appears displaying an image but it doesn't go to next image automatically (and on click of buttons)

Please help to resolve this issue.. 

To see the issue

npm install -g npx

```
npx create-nuxt-app test-bulma (choose bulma as UI framework)
cd test-bulma
npm install
npm install --save bulma-extensions
```

In nuxt.config.js
```
  css: [
    { src: 'bulma-extensions/bulma-carousel/dist/bulma-carousel.min.css', lang: 'css' }
  ],
```

Use carousel in pages/index.vue file.

```
npm run dev
```

Carousel appears on localhost:3000 and doesn't animate or go-to-next-image

**Comment by Wikiki** [comment]
Hi,

do you set <code>data-autoplay="true"</code> attribute to the carousel element to get it auto-scrolling ?

**Comment by o1lab** [comment]
I think not including javascript is the issue. Including js in nuxt.config.js causes following error

```
 ReferenceError: document is not defined
```

However it is not related to this package.

**Comment by johnywhyte** [comment]
Hello, Did you find a way to make the Bulma carousel work in nuxt? I really need this solution. can anyone help out?

**Comment by GreenRidingHood** [comment]
yes.. i can not mak it work in my nuxt project too.. is there any example we can follow
