### ISSUE TITLE
bulma-carousel is not working

### ISSUE THREAD

**Issue by rppf** [Wikiki/bulma-carousel#16]
bulma-carousel is not working in my project
I installed bulma-carousel using yarn.

This is how I import bulma-carousel in
app.scss
![](https://i.imgur.com/HVNYc6O.png)
and in app.js
![](https://i.imgur.com/ezSisF2.png)
and this is how I link in my index
![](https://i.imgur.com/03EC7gW.png)

By the way I'm using Laravel, VueJS, Bulma, Laravel Mix, and webpack.

**Comment by Wikiki** [comment]
Hi @rppf,

is there an error within the javascript browser console ?

**Comment by rppf** [comment]
@Wikiki There's no error in js console.

**Comment by dbcbos** [comment]
Perhaps your missing the font awesome package. I also used Buefy in a project, but it uses the material design icons instead of font awesome. When I added font-awesome it worked.

**Comment by Wikiki** [comment]
Hi @dbcbos,

this extension does not come with any font package. You have to install it as documented in Bulma's documentation.

regards

**Comment by luis7fj** [comment]
![image](https://user-images.githubusercontent.com/5165935/40583006-ace51658-614a-11e8-83a4-f775c7770f15.png)

Utilícelo después de instanciar vuejs. Tube el mismo problema pero solo usando vuejs.

**Comment by alexanderdavide** [comment]
SCSS:
```scss
@import "~bulma-carousel";
```

JS:
```javascript
import bulmaCarousel from "bulma-carousel";

const carousels = bulmaCarousel.attach(".carousel");
```

Mind the default import of `bulmaCarousel` in JS. It mustn't be a named import (import { bulmaCarousel } from "bulma-carousel";).
