### ISSUE TITLE
Previous makes the carousel jump

### ISSUE THREAD

**Issue by JohnMica** [Wikiki/bulma-carousel#17]
as in the codepen https://codepen.io/JohnMica/pen/WMBeyj?editors=1010

active image is image 3
press previous
carousel jumps to image 1 and slides to image 2

not sure why this is (i was expecting a 'reverse' in the slide animation)

**Comment by derevandal** [comment]
This is really happen.
I think that reverse animation wasn't implemented.

**Comment by JohnMica** [comment]
I guess the only option is to use the hero with carousel fade at the moment. 
That one seems to work as intended. 

Regards,

John Mica

**Comment by Wikiki** [comment]
Hi,

actually you're right the fade item is the only one working with Hero currently due to this issue I did not succeed to fix.

I'll try again....

**Comment by Wikiki** [comment]
But...I just see it's happening on classic carousel too :-(

**Comment by Wikiki** [comment]
I fixed it.
I will update the repo soon

**Comment by Wikiki** [comment]
Done. see commit #1355319
