### ISSUE TITLE
Mobile touch events?

### ISSUE THREAD

**Issue by koddr** [Wikiki/bulma-carousel#2]
Hello.

Do you plans add mobile touch events to `bulma-carousel`?
It's very helpful for me (and other site builders with Bulma), because now I use another libs for this with many customizations.

**Comment by Wikiki** [comment]
Hi @koddr,

I will ;-).

**Comment by Wikiki** [comment]
Fixed by #0eaa53d

**Comment by koddr** [comment]
@Wikiki thanks a lot!
