### ISSUE TITLE
Integration with third-party applications

### ISSUE THREAD

**Issue by derevandal** [Wikiki/bulma-carousel#22]
Hi,

I'm using VueJs as my companion on front-end and I wanna change hero nav color based on carousel item displayed. So, I think we can implement Javascript Custom Events to inform DOM what carousel item is on front.

I read about that in https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events

Thanks.

**Comment by Wikiki** [comment]
Hi @derevandal,

I like the idea :-).
I don't have much time those days but feel free to create a PR for it.

**Comment by derevandal** [comment]
@Wikiki this weekend I'll try.
Thanks.

**Comment by Wikiki** [comment]
Please use v2.0.0
