### ISSUE TITLE
top fix navbar is hidding carousel

### ISSUE THREAD

**Issue by zainali95** [Wikiki/bulma-carousel#23]
yup i did the html has-fix-navbar

![image](https://user-images.githubusercontent.com/14200901/37221970-6fab9090-23ed-11e8-9dbd-e8797f66a280.png)

**Comment by Wikiki** [comment]
Hi,

Can you please provide a codepen ?
The body should start under the navbar so the carousel too.
Did you tried to put the carousel within hero ?
