### ISSUE TITLE
Need support for React 

### ISSUE THREAD

**Issue by johnhartman** [Wikiki/bulma-carousel#30]
I'm using bulma in a react app and would like to use bulma-carousel. Unfortunately the .js bindings do not fire because at **DOMContentLoaded** time, the (dynamically created) carousel does not yet exist. Might you repackage the js bindings such that they can be dynamically fired at the  React.Component.componentDidMount() event?

**Comment by Wikiki** [comment]
Hi @johnhartman,

I will completely rewrite the extension and give the possibility to instantiate it manually.

**Comment by Wikiki** [comment]
Why not instantiating it manually within your componentDidMount() event ?
var carousels = document.querySelectorAll('.carousel, .hero-carousel');
  [].forEach.call(carousels, function(carousel) {
    new Carousel(carousel);
  });

**Comment by Wikiki** [comment]
Hi, you can now use the attach static method from your componentDidMount() event (thanks to @anakinjay)

**Comment by johnhartman** [comment]
Sorry for being late in getting back. Unfortunately when the component receives the componentDidMount() call, it has yet to be added to the DOM and consequently the querySelectorAll() call returns no elements.  There is no event in the react lifecycle for when the component has been added to the DOM. I tried creating a pseudo-event for when the component gets a 'Load' event, but 'Load' only occurs on <body>, <frame>, <iframe>, <img>, <input type="image">, <link>, <script>, and <style>, whereas react components ultimately become div element trees, hence no readily available hook.

**Comment by anakinjay** [comment]
@johnhartman 
have you tried putting the attach call inside of a  window.requestAnimationFrame call? you're probably getting caught in the few miliseconds between when the dom element is created and the time when the browser paints the screen.

If not that, a little cheesy, but I think you could use a settimeout of 100ms to give yourself a little buffer for attaching.

**Comment by Wikiki** [comment]
Hi,

the incoming version 2.0.0 should fix this issue with a static attach method and a settimeout of 100ms as suggested by @anakinjay

**Comment by TonyBCodes** [comment]
Hi.  I version 2.0.0 coming soon.  Of course I am using bulma carousel in react.  SO for the moment, I am stuck.

**Comment by AminuSufi585** [comment]
Simply import the `bulmaCarousel` from the bulma-extensions package
```
import bulmaCarousel from 'bulma-extensions/bulma-carousel/dist/js/bulma-carousel';
```
Then call the bulmaCarousel's `attach` method in componentDidMount
```
componentDidMount() {
    bulmaCarousel.attach();
} 
```

**Comment by OlivierJM** [comment]
If anyone come across this issue again @AminuSufi585 comment will fix it.

**Comment by WEEFAA** [comment]
np

> Simply import the `bulmaCarousel` from the bulma-extensions package
> 
> ```
> import bulmaCarousel from 'bulma-extensions/bulma-carousel/dist/js/bulma-carousel';
> ```
> 
> Then call the bulmaCarousel's `attach` method in componentDidMount
> 
> ```
> componentDidMount() {
>     bulmaCarousel.attach();
> } 
> ```

it throws a TypeError Cannot read property 'offsetLeft' of undefined

**Comment by killcodeX** [comment]
Hi, When I am trying to import Bulma from Bulma carousel it showing 'TypeError: Cannot read property 'offsetLeft' of undefined', error. 

```
import bulmaCarousel from 'bulma-carousel';


 useEffect(() => {
        var carousels = bulmaCarousel.attach('.carousel', {
            slidesToScroll: 1,
            slidesToShow: 1
          });
    }, [])
```
