### ISSUE TITLE
Carousel navigation doesn't overlay the picture under iOS

### ISSUE THREAD

**Issue by fklement** [Wikiki/bulma-carousel#34]
I noticed that the carousel `carousel-nav-left` and `carousel-nav-right` does not display correctly under iOS.
I tested it with different iOS Version and devices.
![986437f6-de81-4bf8-9b49-481a8bc68169](https://user-images.githubusercontent.com/7302097/39879415-0d6469e8-547b-11e8-92b1-8f4b68979514.jpg)

**Comment by Wikiki** [comment]
Do you still having the issue with v2 ?

**Comment by fklement** [comment]
On the iPad the problem is solved.
But on iPhone the error presists.
I tested it with an iPhone 5s and an 6s (both are currently running on iOS 10.3.3)
