### ISSUE TITLE
Swipe support?

### ISSUE THREAD

**Issue by Webifi** [Wikiki/bulma-carousel#36]
The [demos/docs](https://wikiki.github.io/components/carousel/) don't reference nor react to swipe left/right gestures in Chrome, but [extension.js](https://github.com/Wikiki/bulma-carousel/blob/master/src/extension.js) seems to have _swipeStart and _swipeEnd methods. 

What am I missing?

**Comment by Wikiki** [comment]
Hi,

you don't miss anything. This functionality has some issues for now. I'm working on it.

**Comment by Wikiki** [comment]
Hi,

it's been fixed.
I'll update the doc soon.
