### ISSUE TITLE
Feature Request: Auto-Scroll

### ISSUE THREAD

**Issue by jethro1991** [Wikiki/bulma-carousel#4]
Auto-scrolling of the carousel would be great!

**Comment by Wikiki** [comment]
Hi @jethro1991,

it's now available.
Please see the documentation page to find out how it works

**Comment by melTr** [comment]
Didn't work for me. I added data-autoplay="true" but nothing happens. However, using buttons to change image works fine.
Thanks

**Comment by Wikiki** [comment]
Is it working for you on the documentation page ?

**Comment by Wikiki** [comment]
Hi @melTr ,

it was a typo error. Fixed ;-)
