### ISSUE TITLE
Swipe/Mouse swipe is not working.

### ISSUE THREAD

**Issue by dumptyd** [Wikiki/bulma-carousel#40]
Tried the first example here https://wikiki.github.io/components/carousel/ on firefox and it's not working.

**Comment by Wikiki** [comment]
Hi, I just tried on my mobile and it's ok for me on chrome and firefox. Weird

**Comment by dumptyd** [comment]
I meant it's not working with mouse.

**Comment by Wikiki** [comment]
I didn't understand. I'll check that
