### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by notchris** [Wikiki/bulma-carousel#41]
Getting this issue when clicking on next / previous buttons to change slides in Chrome 66.

`Unable to preventDefault inside passive event listener invocation.`

Tried to set 'touch-action' style props on all contained elements, but this did not fix the issue.

**Comment by notchris** [comment]
Note: The functionality is working correctly, but the error is thrown on each manual change.

**Comment by Wikiki** [comment]
Hi, it's a known issue. It was just a warning previously.
I'll try to fix that tomorrow.

**Comment by notchris** [comment]
Thanks @Wikiki, I appreciate the quick response.
