### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by rukshandangalla** [Wikiki/bulma-carousel#45]
I checked in the example documentation page and I can see the same error.

![image](https://user-images.githubusercontent.com/1329693/41198253-cbe13912-6c92-11e8-8915-90b0e0aecbd4.png)

Any idea why is this happening?

**Comment by Wikiki** [comment]
Yes, the documentation page has not been updated to the last version. This issue has been fixed with the last release (in standalone version not in the bulma-extensions package)
