### ISSUE TITLE
[Minor] Left to Right Slide Uses White Space Instead of Previous Image

### ISSUE THREAD

**Issue by Laraveldeep** [Wikiki/bulma-carousel#48]
Default slide direction of carousel is right to left. In this direction up coming image pushes the current image to left. However when we press navigation left arrow to slide in opposite direction, it used white space instead.

Loop should be continuity of images in either direction.

Thanks!

**Comment by Wikiki** [comment]
How many images do you have in your Carousel ? Cause it's working as expected in documentation

**Comment by Laraveldeep** [comment]
Ok. 

I was testing with only 2 images. It behaves correctly when there are minimum of 3 images. Thanks!
