### ISSUE TITLE
Carousel with multiple data items does not resize when resizing browser

### ISSUE THREAD

**Issue by walpoletim-bjss** [Wikiki/bulma-carousel#49]
When you have a carousel with multiple items shown, then when the browser size is changed, the carousel does not resize

**Comment by iqbalaqaba** [comment]
It happened to me, whenever i'm trying to resize the browser, the carousel didn't work well. It's even happened on its doc site, try to refresh the browser couple times and resize the window. This happened.
I hope they fix it asap

![screenshot_2](https://user-images.githubusercontent.com/20835372/46258965-734c8f00-c4fc-11e8-9861-c4f0f551a228.png)

**Comment by Wikiki** [comment]
Hi, I'll have a loot at it soon

**Comment by tmm1** [comment]
I think this is probably due to fixed height set in fade mode:

https://github.com/Wikiki/bulma-carousel/blob/033a07476ada12ed986ad407539a1d669f943202/src/js/index.js#L143-L156

**Comment by jasoncostello** [comment]
FWIW, this behavior also happens when only showing single images too (set to fade)
