### ISSUE TITLE
bulmaCarousel.attach() returns 0 instances

### ISSUE THREAD

**Issue by bfioca** [Wikiki/bulma-carousel#54]
I know my carousel is working because I can click the navigation elements and it slides correctly. 

Also worth noting is if I leave off the `bulmaCarousel.attach()` it stops working. 

However, 
```
  var carousels = bulmaCarousel.attach();
  console.log(carousels.length);
```
always returns 0 for me, and I can't get a hold of any of the instances to listen to their events. Even if I try to select them directly with jQuery selectors. 

Any ideas?

**Comment by bfioca** [comment]
ok, it's actually because it returns the array before the elements are pushed (it uses a timeout):

`value: function attach() {
      var selector = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : '.carousel, .hero-carousel';
      var options = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};

      var instances = new Array();

      var elements = document.querySelectorAll(selector);
      [].forEach.call(elements, function (element) {
        setTimeout(function () {
          instances.push(new bulmaCarousel(element, options));
        }, 100);
      });
      return instances;
    }
`

that seems... tricky to cope with. the way I'm working around it is wrapping my call in a 200ms timeout.

**Comment by Wikiki** [comment]
I have to remove the setTimeout which was a old workaround to work with react.
I'll do it soon.
