### ISSUE TITLE
Ability to change the data-size for different viewports

### ISSUE THREAD

**Issue by MHassanSaqib** [Wikiki/bulma-carousel#57]
Hi, It would greatly help to change the data-size property for different viewports. Could you please help me to make it my project.

**Comment by SandPipper** [comment]
+

**Comment by raikusy** [comment]
@Wikiki when will this issue be fixed? Is there any work around for now?

**Comment by Wikiki** [comment]
Hi,

I'm woeking on the next release. It will integrates that and should be released before the end of the year

**Comment by AlexFence** [comment]
hello there, what exactly is the status of this?

**Comment by Wikiki** [comment]
Hi,

new version almost finished (I don't have enough time to finalize it currently). After that I have to update documentation and plublish it (I hope being able to do it before mid february)
