### ISSUE TITLE
Feature Request: Nav dots

### ISSUE THREAD

**Issue by estooong** [Wikiki/bulma-carousel#59]
Request to add navigation dots to bulma-carousel if possible. Thank you :smile:

**Comment by Wikiki** [comment]
Hi its coming soon 😉

**Comment by fabiopedrosa** [comment]
@Wikiki any update? can I help with something?

**Comment by Wikiki** [comment]
Hi,

It should be release before the end of the year.

**Comment by lludol** [comment]
Hello,

@Wikiki any update?
Your carousel is nice but my client want to display "dots" instead of arrows 😑

**Comment by Wikiki** [comment]
Hi,

sorry for the delay I'm still fixing some bugs on the next release but not have much time thes days.
