### ISSUE TITLE
How to pause auto play when user interacts with carousel ?

### ISSUE THREAD

**Issue by YajanaRao** [Wikiki/bulma-carousel#64]
Auto play does not pause when user interacts with the carousel item. Is there any option to pause the auto play on hover?

**Comment by Wikiki** [comment]
Hi,

it's in progress in the upcoming release.
keep in touch.

**Comment by YajanaRao** [comment]
Do we have any documentation on implementing the above feature

**Comment by Wikiki** [comment]
Have a look at the documentation page and especially at the option "pauseOnHover"
