### ISSUE TITLE
Animated Slider

### ISSUE THREAD

**Issue by Yard8** [Wikiki/bulma-carousel#7]
Hi!

Noticed a slight issue when using carousel-animate-fade, the first slide doesn't apply the fade animation correctly when switching to the next slide. There after it works correctly, can you replicate this issue?

**Comment by Wikiki** [comment]
Can you please provide a working codepen ? Because I do not succeed to reproduce this issue.

**Comment by Wikiki** [comment]
Hi, 

any news ?
Anyone else facing this issue ?

**Comment by dnhyde** [comment]
Hi I am facing the same issue.
Here is the working [codepen](https://codepen.io/anon/pen/BrxzEo). Just change the `carousel-animate-slide` with `carousel-animate-fade` and you shall see the carousel becomes white.

Thanks for the amazing work!

**Comment by Wikiki** [comment]
Please use v2.0.0
