### ISSUE TITLE
Css has a dependency on images left.svg and right.svg so package doesn't work out of the box

### ISSUE THREAD

**Issue by gdestree** [Wikiki/bulma-carousel#70]
When using bulma-carousel@4.0.2 the package has a dependence on the images left.svg and right.svg and errors on initializing webpack. 
Is this intended? I don't read anywhere that I should be adding any assets.

**Comment by Wikiki** [comment]
Hi,

Nope it's an issue. I forgot to replace those images by svg content.
I'll fix it.
