### ISSUE TITLE
pagination documentation

### ISSUE THREAD

**Issue by tehfink** [Wikiki/bulma-carousel#77]
On the documentation page:
https://demo.creativebulma.net/components/carousel//#options

It says that the default value for `pagination` is `HH:mm`. Is it correct?
```
Name | Description | Default value
pagination | Display pagination bullets | HH:mm
```

**Comment by Wikiki** [comment]
No. It's a mistake. This option needs a boolean value (True to activate pagination else False)

**Comment by Wikiki** [comment]
I'll update the doc

**Comment by tehfink** [comment]
@Wikiki Similar for "navigationSwipe": the docs say the default value is "MM/DD/YYYY"

**Comment by kirillarutyunov** [comment]
@Wikiki  I fixed this problem, you can check PR

**Comment by eman1986** [comment]
still showing the wrong info, hope it gets fixed soon
