### ISSUE TITLE
I just doesn't work

### ISSUE THREAD

**Issue by trsh** [Wikiki/bulma-carousel#83]
I took example code 

https://pastebin.com/0ZauxjBL

pasted in clean HTML. Filled the contents, and nothing...

AS well i could not catch any working live demos :(

**Comment by trsh** [comment]
My bad

**Comment by 0xAcid** [comment]
@trsh I cannot seem to make it work either. Any tips ? (Would also be useful for future users)

**Comment by Wikiki** [comment]
@0xAcid : see demo here (based on the code gave by @trsh): https://codepen.io/wikiki/pen/bGdzdre
